### ISSUE TITLE
Templates of 'kdc.conf' and 'krb5.conf' define some sections twice

### ISSUE THREAD

**Issue by jusstol** [TOSIT-IO/tdp-collection-extras#32]
This issue follows #31.

In the `ansible-ldap-kerberos` rôle, the templates of _kdc.conf_ and _krb5.conf_ do not match MIT Kerberos recommended structure. Everything works fine since those two files are merged eventually but that means some sections are defined twice.

Sections of _roles/ansible-ldap-kerberos/templates/krb5.conf.j2_ :
```
[logging]
...
[libdefaults]
...
[realms]
...
[domain_realm]
```
Following MIT documentation (https://web.mit.edu/kerberos/krb5-1.12/doc/admin/conf_files/krb5_conf.html#sections), the `logging` section should not be here.

Sections of _roles/ansible-ldap-kerberos/templates/kdc.conf.j2_ :
```
[logging]
...
[libdefaults]
...
[realms]
...
[domain_realm]
...
[dbdefaults]
...
[dbmodules]
```
Following MIT documentation (https://web.mit.edu/kerberos/krb5-1.12/doc/admin/conf_files/kdc_conf.html#sections), the `libdefaults` and `domain_realms` sections should not be here.

**Comment by rpignolet** [comment]
This should be fixed with https://github.com/TOSIT-IO/tdp-collection-prerequisites/pull/10, `ansible-ldap-kerberos` will be removed (see #53).

Do not hesitate to open the issue in https://github.com/TOSIT-IO/tdp-collection-prerequisites if this is not fixed.
