### ISSUE TITLE
NiFi Integration

### ISSUE THREAD

**Issue by pm-McFly** [TOSIT-IO/tdp-collection-extras#34]
Please consider the integration of NiFi into this distro. It would help on the data transfer and transformation between the all other components you have.

Othe related issues:
- https://github.com/TOSIT-IO/TDP/issues/15
- https://github.com/TOSIT-IO/tdp-getting-started/issues/108

**Comment by Nuttymoon** [comment]
@pm-McFly thank you for your contribution to TDP!
In a fully open-source approach, all Issues/Pull Requests are fairly examined for integration.

Your issue/PR integrates a new technology / service / component to TDP. Can you please open a **new discussion** for validation before any implementation. See the [TDP new component proposal guidelines](https://github.com/orgs/TOSIT-IO/discussions/25) for details on how to organize your request.

[Click here to open a new TDP discussion](https://github.com/orgs/TOSIT-IO/discussions)

**Comment by rpignolet** [comment]
Close as inactive.
