### ISSUE TITLE
Add Mitogen support for Livy and Livy Spark3

### ISSUE THREAD

**Issue by rpignolet** [TOSIT-IO/tdp-collection-extras#67]
When running meta playbook `playbooks/meta/livy.yml`:

```
TASK [tosit.tdp.kerberos : Create principal for livy/edge-01.tdp] *********
fatal: [edge-01]: FAILED! => 
  msg: The module krb_principal was not found in configured module paths.
```
The cause is Mitogen do not resolve correctly modules imports. Add `strategy: linear` to Livy playbooks which do not support Mitogen to disable it.

**Comment by leopaul36** [comment]
I think we also need to do this for Kafka's role.

@Edouard-R had some issues with this role that looks related to Mitogen:

```
ERROR! Unexpected Exception, this is probably a bug: module 'ansible_collections.ansible.builtin.plugins.action' has no attribute 'ActionBase'
```

**Comment by rpignolet** [comment]
I do not have issue with Kafka playbooks related to Mitogen. Which playbook is not working ?
