### ISSUE TITLE
We can't do this just to get a working webhdfs endpoint, as soon as a failover occurs, hue won't work anymore ?

### ISSUE THREAD

**Issue by DanielJohnHarty** [TOSIT-IO/tdp-collection-extras#9]
We can't do this just to get a working webhdfs endpoint, as soon as a failover occurs, hue won't work anymore ?

_Originally posted by @gboutry in https://github.com/TOSIT-IO/tdp-collection-extras/pull/8#discussion_r840707592_

**Comment by leopaul36** [comment]
Made a clearer issue to track this: https://github.com/TOSIT-IO/tdp-collection-extras/issues/14
