### ISSUE TITLE
Add Fluentbit configuration to ZooKeeper Kafka

### ISSUE THREAD

**Issue by leopaul36** [TOSIT-IO/tdp-collection-extras#96]
We need to add Fluentbit properties to ZooKeeper Kafka to be on par with the changes of https://github.com/TOSIT-IO/tdp-collection/pull/652

**Comment by rpignolet** [comment]
Closing since https://github.com/TOSIT-IO/tdp-collection-prerequisites/pull/63 won't be merged in favor of https://github.com/TOSIT-IO/tdp-observability/pull/24
